/**
 * Generates dist/css/tokens.css, dist/css/tailwind.css and dist/tokens.json
 * from src/tokens. Run with plain `node` (Node ≥ 22.6 strips types).
 *
 * Kept as string templating over one typed object on purpose: two of the
 * three outputs are Tailwind-specific syntax (`@theme inline`,
 * `--text-x--line-height`, `@utility`) that no token tool has a format for,
 * and this is short enough to read in one sitting.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { brand } from "../src/tokens/brand.ts"
import { colors, type Mode } from "../src/tokens/colors.ts"
import { fonts, fontStack } from "../src/tokens/fonts.ts"
import { radii } from "../src/tokens/radii.ts"
import { shell } from "../src/tokens/shell.ts"
import { type, typeSize, type TypeStep } from "../src/tokens/type.ts"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")) as { version: string }

const LIGHT = ':root, .light, [data-theme="light"]'
const DARK = '.dark, [data-theme="dark"]'
const DARK_MEDIA = ':root:not(.light):not([data-theme="light"])'

const indent = (lines: string[], depth: number) => lines.map((l) => "  ".repeat(depth) + l).join("\n")

function colorLines(mode: Mode): string[] {
  return Object.entries(colors).map(([role, pair]) => `--${role}: ${pair[mode]};`)
}

const radiusLines = [
  `--radius: ${radii.base / 16}rem;`,
  `--radius-sm: ${radii.sm / 16}rem;`,
  `--radius-md: var(--radius);`,
  `--radius-lg: ${radii.lg / 16}rem;`,
  `--radius-xl: ${radii.xl / 16}rem;`,
  `--radius-2xl: ${radii["2xl"] / 16}rem;`,
]

const typeLines = Object.entries(type).flatMap(([name, step]) => [
  `--text-${name}: ${typeSize(step)};`,
  `--text-${name}--line-height: ${step.lineHeight};`,
])

const fontLines = (Object.keys(fonts) as (keyof typeof fonts)[]).map(
  (role) => `--font-${role}: ${fontStack(role)};`,
)

const brandLines = [
  `--brand-gradient: linear-gradient(${brand.gradient.angle}deg, ${brand.gradient.stops
    .map((s) => `${s.color} ${s.at}%`)
    .join(", ")});`,
]

/**
 * The colour block is emitted three times — light, dark by class/attribute,
 * dark by OS preference — so one stylesheet serves next-themes apps (the
 * class is always present, so the media branch never fights it) and static
 * sites with no JS at all.
 */
function themeBlock(extraLight: string[], extraDark: string[]): string {
  const light = [`color-scheme: light;`, ...colorLines("light"), ...extraLight]
  const dark = [`color-scheme: dark;`, ...colorLines("dark"), ...extraDark]
  return [
    `@layer base {`,
    `  ${LIGHT} {`,
    indent(light, 2),
    `  }`,
    ``,
    `  ${DARK} {`,
    indent(dark, 2),
    `  }`,
    ``,
    `  @media (prefers-color-scheme: dark) {`,
    `    ${DARK_MEDIA} {`,
    indent(dark, 3),
    `    }`,
    `  }`,
    `}`,
  ].join("\n")
}

const header = (what: string) =>
  `/* @aisocratic/stoa ${pkg.version} — ${what}. Generated by scripts/build-css.ts; do not edit. */\n`

/* ---------------------------------------------------------------- tokens.css */
const tokensCss =
  header("plain CSS custom properties, no Tailwind") +
  themeBlock([...radiusLines, ...typeLines, ...fontLines, ...brandLines], []) +
  "\n"

/* -------------------------------------------------------------- tailwind.css */
const themeType = [
  `/* The type scale is a plain @theme, not inline, so var(--text-lead) is`,
  ` * readable from hand-written CSS too. */`,
  `@theme {`,
  indent(typeLines, 1),
  `}`,
].join("\n")

const themeInline = [
  `@theme inline {`,
  indent(
    Object.keys(colors).map((role) => `--color-${role}: var(--${role});`),
    1,
  ),
  ``,
  indent(
    [
      `--radius-sm: ${radii.sm / 16}rem;`,
      `--radius-md: var(--radius);`,
      `--radius-lg: var(--radius);`,
      `--radius-xl: ${radii.xl / 16}rem;`,
      `--radius-2xl: ${radii["2xl"] / 16}rem;`,
    ],
    1,
  ),
  ``,
  indent(fontLines, 1),
  ``,
  indent(
    [
      `--shadow-glow: 0 0 8px 2px var(--tw-shadow-color);`,
      `--animate-skeleton-pulse: skeleton-pulse 2.5s ease-in-out infinite;`,
      `@keyframes skeleton-pulse {`,
      `  0%, 100% { opacity: 1; }`,
      `  50% { opacity: 0.4; }`,
      `}`,
    ],
    1,
  ),
  `}`,
].join("\n")

const baseCss = readFileSync(join(ROOT, "src/css/base.css"), "utf8")

const tailwindCss =
  header("Tailwind v4 theme. Import AFTER `@import \"tailwindcss\"`") +
  themeBlock([`--radius: ${radii.base / 16}rem;`, ...brandLines], []) +
  "\n\n" +
  themeType +
  "\n\n" +
  themeInline +
  "\n\n" +
  baseCss

/* --------------------------------------------------------------- tokens.json */
const tokensJson = {
  version: pkg.version,
  color: {
    light: Object.fromEntries(Object.entries(colors).map(([k, v]) => [k, v.light])),
    dark: Object.fromEntries(Object.entries(colors).map(([k, v]) => [k, v.dark])),
  },
  type: Object.fromEntries(
    (Object.entries(type) as [string, TypeStep][]).map(([k, s]) => [
      k,
      { px: s.px, ...(s.max ? { max: s.max } : {}), css: typeSize(s), lineHeight: s.lineHeight, note: s.note },
    ]),
  ),
  radius: radii,
  font: fonts,
  shell,
  brand,
}

mkdirSync(join(ROOT, "dist/css"), { recursive: true })
writeFileSync(join(ROOT, "dist/css/tokens.css"), tokensCss)
writeFileSync(join(ROOT, "dist/css/tailwind.css"), tailwindCss)
writeFileSync(join(ROOT, "dist/tokens.json"), JSON.stringify(tokensJson, null, 2) + "\n")
console.log("wrote dist/css/tokens.css, dist/css/tailwind.css, dist/tokens.json")
